# Generated by Django 5.2.6 on 2025-09-17 00:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('merchandise', 'Merchandise'), ('accessories', 'Accessories'), ('shoe', 'Shoe'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('player', 'Player')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
